# Generated by Django 5.1.2 on 2024-10-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutmephoto_delete_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
