# Generated by Django 5.1.2 on 2024-10-13 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='publication',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
