# Generated by Django 5.1.2 on 2024-10-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_publication_publication_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('session_length', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('installment_available', models.BooleanField(default=False)),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
