# Generated by Django 5.1.2 on 2024-10-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_diploma'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPname', models.TextField(blank=True, null=True)),
                ('InnInfo', models.CharField(blank=True, max_length=25, null=True)),
                ('OgrnInfo', models.CharField(blank=True, max_length=25, null=True)),
                ('Adress', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
